import { DatabaseModel } from 'ontime-types';

export const dbModel: DatabaseModel = {
  rundown: [],
  eventData: {
    title: '',
    publicUrl: '',
    publicInfo: '',
    backstageUrl: '',
    backstageInfo: '',
  },
  settings: {
    app: 'ontime',
    version: 2,
    serverPort: 4001,
    editorKey: null,
    operatorKey: null,
    timeFormat: '24',
    language: 'en',
  },
  viewSettings: {
    overrideStyles: false,
    normalColor: '#ffffffcc',
    warningColor: '#FFAB33',
    warningThreshold: 120000,
    dangerColor: '#ED3333',
    dangerThreshold: 60000,
    endMessage: '',
  },
  aliases: [],
  userFields: {
    user0: 'user0',
    user0Enabled: false,
    user1: 'user1',
    user1Enabled: false,
    user2: 'user2',
    user2Enabled: false,
    user3: 'user3',
    user3Enabled: false,
    user4: 'user4',
    user4Enabled: false,
    user5: 'user5',
    user5Enabled: false,
    user6: 'user6',
    user6Enabled: false,
    user7: 'user7',
    user7Enabled: false,
    user8: 'user8',
    user8Enabled: false,
    user9: 'user9',
    user9Enabled: false,
  },
  osc: {
    portIn: 8888,
    portOut: 9999,
    targetIP: '127.0.0.1',
    enabledIn: false,
    enabledOut: false,
    subscriptions: {
      onLoad: [],
      onStart: [],
      onPause: [],
      onStop: [],
      onUpdate: [],
      onFinish: [],
    },
  },
  departments: [],
  sheetsSync: {
    enabled: false,
    sheetId: '',
    sheetName: '',
    apiKey: '',
  },
};
